version: '3'
services:
    lyr-service:
        #restart: always #Comment this out when testing locally.
        image: bdkiran/lyr-service
        environment:
            - ES_CONNECTION_STRING=http://10.128.0.2:9200
            - TOKEN_SECRET=myDawg
        ports:
            - 9000:9000
    user-service:
        #restart: always #Comment this out when testing locally.
        image: bdkiran/nocap-user-service
        environment:
            #Postgres variables
            - PGHOST=10.128.0.2
            - PGUSER=pgUser
            - PGDATABASE=nocap
            - PGPASSWORD=pgPassword
            - PGPORT=5432
            #google auth variables
            - CLIENT_ID=462139200149-n6ra1f09mhm7oie6fc29bah3pcc386j7.apps.googleusercontent.com
            - CLIENT_SECRET=ztWzMtZOXC1OE2qcMC_XHDN_
            #JWT variables
            - TOKEN_SECRET=myDawg
        ports:
            - 8080:8080