version: '3'
services:
    lyr-service:
        #restart: always #Comment this out when testing locally.
        image: bdkiran/lyr-service
        environment:
            - ES_CONNECTION_STRING=http://192.168.1.251:9200
            - TOKEN_SECRET=mySecret
        network_mode: bridge
        ports:
            - 9000:9000
    user-service:
        #restart: always #Comment this out when testing locally.
        image: bdkiran/nocap-user-service
        environment:
            #Postgres variables
            - PGHOST=192.168.1.28
            - PGUSER=postgres
            - PGDATABASE=nocap
            - PGPASSWORD=postgres
            - PGPORT=5432
            #google auth variables
            - CLIENT_ID=462139200149-n6ra1f09mhm7oie6fc29bah3pcc386j7.apps.googleusercontent.com
            - CLIENT_SECRET=ztWzMtZOXC1OE2qcMC_XHDN_
            #JWT variables
            - TOKEN_SECRET=mySecret
        ports:
            - 8080:8080